// https://cz-git.qbb.sh/zh/config/


module.exports = {
  extends: ['@commitlint/config-conventional'],
  prompt: {
    messages: {
      type: '选择你要提交的类型 :',
      scope: '选择一个提交范围（可选）:',
      customScope: '请输入自定义的提交范围 :',
      subject: '填写简短精炼的变更描述 :\n',
      body: '填写更加详细的变更描述（可选）。使用 "|" 换行 :\n',
      breaking: '列举非兼容性重大的变更（可选）。使用 "|" 换行 :\n',
      footerPrefixesSelect: '选择关联issue前缀（可选）:',
      customFooterPrefix: '输入自定义issue前缀 :',
      footer: '列举关联issue (可选) 例如: #31, #I3244 :\n',
      generatingByAI: '正在通过 AI 生成你的提交简短描述...',
      generatedSelectByAI: '选择一个 AI 生成的简短描述:',
      confirmCommit: '是否提交或修改commit ?',
    },
    // prettier-ignore
    types: [
        { value: "feat",     name: "feat:        ✨  新增功能", emoji: ":sparkles:" },
        { value: "fix",      name: "fix:         🐛  修复缺陷", emoji: ":bug:" },
        { value: "chore",    name: "chore:       🔨  对构建过程或辅助工具和库的更改（不影响源文件）", emoji: ":hammer:"},
        { value: "docs",     name: "docs:        📝  文档变更", emoji: ":memo:" },
        { value: "style",    name: "style:       💄  代码格式（不影响功能，例如代码格式修正）", emoji: ":lipstick:" },
        { value: "build",    name: "build:       📦️  构建流程、外部依赖变更（如升级 npm 包、修改 vite 配置等）", emoji: ":package:"},
        { value: "perf",     name: "perf:        ⚡️  性能优化", emoji: ":zap:" },
        { value: "revert",   name: "revert:      ⏪️  回滚 commit",emoji: ":rewind:"},
        { value: "-",        name: "-:           ⚠️   追加提交上一次commit, 尽量不要使用,谁用谁就是最懒的,你用你就是最懒的",emoji: ":warn:"},
        { value: "refactor", name: "refactor:    🚧️  代码重构（不包括 bug 修复、功能新增）", emoji: ":recycle:" },
        { value: "test",     name: "test:        ✅  添加疏漏测试或已有测试改动", emoji: ":white_check_mark:"},
        { value: "ci",       name: "ci:          🎡  修改 CI 配置、脚本",  emoji: ":ferris_wheel:"},
      ],
    useEmoji: true,
    emojiAlign: 'center',
    useAI: false,
    aiNumber: 1,
    themeColorCode: '',
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: [],
    issuePrefixes: [
      { value: 'closed', name: 'closed:   ISSUES has been processed' },
    ],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    maxHeaderLength: Infinity,
    maxSubjectLength: Infinity,
    minSubjectLength: 0,
    scopeOverrides: undefined,
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: '',
  },
};
